apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodtstore
  labels:
    app: mongodtstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodtstore
  template:
    metadata:
      labels:
        app: mongodtstore
    spec:
      containers:
      - name: mongodtstore
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodtstore
              key: database-name
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodtstore
              key: database-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodtstore
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodtstore
  labels:
    app: mongodtstore
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodtstore