apiVersion: apps/v1
kind: Deployment
metadata:
  name: routergateway
  labels:
    app: routergateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routergateway
  template:
    metadata:
      labels:
        app: routergateway
    spec:
      containers:
      - name: routergateway
        image: jamesmedice/routergateway
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: routergateway
  labels:
    app: routergateway
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: routergateway
  type: NodePort