server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: business
        uri: http://business:8080/
        predicates:
        - Path=/business/**
      - id: director
        uri: http://director:8080/
        predicates:
        - Path=/director/**
      - id: enterprise
        uri: http://enterprise:8080/
        predicates:
        - Path=/enterprise/**
      - id: seller
        uri: http://seller:8080/
        predicates:
        - Path=/seller/**